name: nuget publish
inputs:
  registry:
    required: false
    default: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  token:
    required: true
runs:
  using: composite
  steps:
  - name: nuget push to ${{ inputs.registry }}
    shell: bash
    run: |-
      fdfind --no-ignore nupkg$
      fdfind --no-ignore nupkg$ -x dotnet nuget push {} --api-key ${{ inputs.token }}  --source "${{ inputs.registry }}"
