name: nuget publish
inputs:
  path:
    description: path from where to run the actions
    type: string
    required: false
    default: ${{ github.workspace }}
  registry:
    required: false
    default: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  token:
    required: true
runs:
  using: composite
  steps:
  - name: nuget push to ${{ inputs.registry }}
    shell: bash
    run: |-
      pushd ${{ inputs.path }}
      fdfind -tf --no-ignore "[^(\.symbols)]\.nupkg$"
      fdfind -tf --no-ignore "[^(\.symbols)]\.nupkg$" -x dotnet nuget push {} --api-key ${{ inputs.token }}  --source "${{ inputs.registry }}"  --skip-duplicate
      popd
