name: nuget publish
inputs:
  path:
    description: path from where to run the actions
    type: string
    required: false
    default: ${{ github.workspace }}
  registry:
    required: false
    default: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  token:
    required: true
runs:
  using: composite
  steps:
  - name: nuget push to ${{ inputs.registry }}
    shell: pwsh
    run: |-
      Push-Location ${{ inputs.path }}

      $token = "${{ inputs.token }"
      $registry = "${{ inputs.registry }}"

      fdfind -tf --no-ignore "[^(\.symbols)]\.nupkg$"
      foreach ($package in @(fdfind -tf --no-ignore "[^(\.symbols)]\.nupkg$"))
      {
        echo "nuget push $package --api-key $token  --source $registry  --skip-duplicate"
        nuget push $package --api-key $token  --source $registry  --skip-duplicate
      }

      Pop-Location
