name: nuget pack
inputs:
  framework:
    required: false
runs:
  using: composite
  steps:
  - uses: "./.github/actions/build-release-dll"
    with:
      framework: "${{ inputs.framework }}"
  - name: Run nuget pack with ${{ inputs.framework }}
    shell: bash
    run: |-
      framework=${{ inputs.framework }}
      for a in $(rg --files-with-matches  --type-add "csp:*.csproj" -tcsp "${framework}"); do
        dotnet pack -c Release -p:TargetFramework=${framework} $a || echo "Error"
      done
      fdfind --no-ignore nupkg$
