name: nuget pack
inputs:
  path:
    description: path from where to run the actions
    type: string
    required: false
    default: ${{ github.workspace }}
  configuration:
    description: configuration to build and pack for (Debug, Release, ...)
    type: string
    required: false
    default: Release
  framework:
    description: framework to build for (net8.0, netstandard2.1, ...)
    type: string
    required: true
runs:
  using: composite
  steps:
  - uses: kagekirin/gha-dotnet/.github/actions/build@main
    with:
      path: ${{ inputs.path }}
      configuration: ${{ inputs.configuration }}
      framework: ${{ inputs.framework }}
  - name: Run nuget pack with ${{ inputs.framework }}
    shell: pwsh
    run: |-
      Push-Location ${{ inputs.path }}

      $configuration = "${{ inputs.configuration }}"
      $framework = "${{ inputs.framework }}"

      foreach ($project in @(rg --files-with-matches  --type-add "csp:*.csproj" -tcsp "${framework}"))
      {
        echo "Packing $project with $framework in $configuration"
        echo "dotnet pack -c ${{ inputs.configuration }} -p:TargetFramework=${framework} $a"
        dotnet pack -c ${{ inputs.configuration }} -p:TargetFramework=${framework} $a
      }

      fdfind -tf --no-ignore nupkg$

      Pop-Location
