name: Fetch NuGet package from registry
inputs:
  path:
    description: path from where to run the actions
    type: string
    required: false
    default: ${{ github.workspace }}
  package:
    required: true
  registry:
    required: false
    default: '' #https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  framework:
    required: false
    default: ''
  version:
    required: false
    default: ''
  prerelease:
    required: false
    type: boolean
    default: false
  outdir:
    required: false
    default: ''
runs:
  using: composite
  steps:
  - name: Fetch package ${{ inputs.package }}
    shell: pwsh
    run: |-
      Push-Location ${{ inputs.path }}
      nuget help install

      $source = "${{ inputs.registry }}"
      $source = (! [string]::IsNullOrEmpty( $source )) ? "-Source $source" : ""

      $framework = "${{ inputs.framework }}"
      $framework = (! [string]::IsNullOrEmpty( $framework )) ? "-Framework $framework" : ""

      $version = "${{ inputs.version }}"
      $version = (! [string]::IsNullOrEmpty( $version )) ? "-version $version" : ""

      $prerelease = ($${{ inputs.prerelease}}) ? "-Prerelease" : ""

      $outdir = "${{ inputs.outdir }}"
      $outdir = (! [string]::IsNullOrEmpty( $outdir )) ? "-OutputDirectory $outdir" : ""

      echo "nuget install ${{ inputs.package }} $version $prerelease -DirectDownload -NonInteractive  $outdir $framework $source"
      nuget install ${{ inputs.package }} $version $prerelease -DirectDownload -NonInteractive  $outdir $framework $source

      Pop-Location
