name: Add NuGet Registry
description: >
  GitHub action to add a NuGet registry

inputs:
  name:
    description: Name/Alias of the NuGet registry to add (must be unique)
    required: true
  registry:
    description: URL of the NuGet registry to add
    required: false
    default: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  username:
    description: A valid username for the given registry
    required: false
    default: ${{ github.repository_owner }}
  token:
    description: A GitHub token with "packages:read" permissions for the given registry
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
  - name: Add NuGet source ${{ inputs.registry }}
    if: inputs.registry != 'https://api.nuget.org/v3/index.json'
    shell: bash
    run: |-
      dotnet nuget add source --username "${{ inputs.username }}" --password "${{ inputs.token }}" --store-password-in-clear-text --name ${{ inputs.name }} "${{ inputs.registry }}"
