name: Add NuGet Registry
inputs:
  name:
    required: true
  registry:
    required: false
    default: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  username:
    required: true
  token:
    required: true
runs:
  using: composite
  steps:
  - name: Add NuGet source ${{ inputs.registry }}
    shell: bash
    run: |-
      dotnet nuget add source --username "${{ inputs.username }}" --password "${{ inputs.token }}" --store-password-in-clear-text --name ${{ inputs.name }} "${{ inputs.registry }}"
